using ConsoleApp1.Weapons;

namespace ConsoleApp1.Characters.Warriors
{
    public class Warrior
    {
        public static int id;

        private int height;
        private int weight;
        private int age;
        private string name;
        private Sword swordWeapon;


        public int Age
        {
            get
            {

                return age;
            }
            set
            {
                if (value >= 18 && value <= 45)
                {
                    age = value;
                }
                else
                {
                    throw new ArgumentOutOfRangeException(string.Empty, $@"Improper age for Warrior: {name}");
                }
            }
        }
        protected internal int Height 
        {
            get
            {
                return height;
            }

            set
            {
                height = value;
            }
        }
        public int Weight
        {
            get
            {
                return weight;
            }
            set
            {
                weight = value;
            }
        }
        public string Name 
        { 
            get
            {
                return name;
            } 
            set
            {
                name = value;
            }
        }
        public Sword SwordWeapon 
        { 
            get
            {
                return this.swordWeapon;
            } 
            set
            {
                this.swordWeapon = value;
            }
        }

        public Warrior()
            : this(100, 100) // Calls constructor below it
        {
            //this.Name = "Warrior";
            //this.Age = 18;
            //this.SwordWeapon = new Sword(); // This code is run below because the rest of the constructor
                                              // code is executed as well
        }

        public Warrior(int height, int weight)
            : this(height, weight, "Warrior")
        {
            //this.Height = height;
            //this.Weight = weight;
            //this.Name = "Warrior";
            //this.Age = 18;
            //this.SwordWeapon = new Sword();
        }

        public Warrior(int height, int weight, string name)
        {
            this.Height = height;
            this.Weight = weight;
            this.Name = name;
            this.Age = 18;
            this.SwordWeapon = new Sword();
        }
        
        //Autogenerated with CTRL + . + ENTER
        //public Warrior(int height, int weight, int age, string name, Sword swordWeapon)
        //{
        //    this.height = height;
        //    this.weight = weight;
        //    this.age = age;
        //    this.name = name;
        //    this.swordWeapon = swordWeapon;
        //}

        public void Greetings(string name)
        {
            Console.WriteLine($@"{this.name}, greets {name}!");
        }
    }
}